### PR TITLE
add: cowsay command in fun category

### PR DESCRIPTION
**Pull request by ArnavK-09**
```
 _________
< Discord >
 ---------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

### CODE REVIEW

**Comment by ArnavK-09** [comment]
Ah "cobst" 🗿

**Comment by ArnavK-09** [comment]
- [ x] @DeltaCoderr 🗿

**Comment by ArnavK-09** [comment]
@DeltaCoderr review🗿

**Comment by DeltaCoderr** [comment]
Hey @ArnavK-09, We don't really need this command as for now since the main focus here is to shift the codebase to newer version of discord.js (which is in another branch). So I'll have to close this Pull Request for now. If you do wish to contribute you can make a pull request on the djs-v14 branch instead!

**Pull request closed without merging**
