### PR TITLE
Yp/issue 114

### PR DESCRIPTION
**Pull request by Yash-271120**
Changes and refactoring regarding converting commands to slash commands (#114 )

### CODE REVIEW

**Comment by Yash-271120** [comment]
@DeltaCoderr If this looks good, Then I will do other nsfw in similar way. :)

**Comment by DeltaCoderr** [comment]
Most of it looks good, only question I got is the interactionCreate event, since all the events should go under the Events folder. Do you mind shifting that code into the folder by making a new file itself? @Yash-271120

**Comment by Yash-271120** [comment]
Ok. I'll shift it in the Events folder.

**Review by DeltaCoderr — APPROVED** [review]
This should be good.

**Pull request merged**
