### PR TITLE
Improved loggers

### PR DESCRIPTION
**Pull request by gonzyui**

### CODE REVIEW

**Comment by DeltaCoderr** [comment]
Still need a `success` and a `debug` one.

**Comment by gonzyui** [comment]
you can rename `info` to success and `stacktrace` to debug

**Comment by DeltaCoderr** [comment]
Well, `info` and `success` are completely different.  the `success` one uses a green color, Meanwhile Info uses blue.

**Comment by gonzyui** [comment]
It seems be fixed now

**Review by DeltaCoderr — APPROVED** [review]
Thanks!

**Pull request merged**
